<?php

namespace SagePHP\Test;

use SagePHP\Configuration\HostsFile;

class HostsFileTest extends \PHPUnit_Framework_TestCase
{
    public function setUp()
    {     $this->fixturePath = __DIR__ . "/../fixtures/hosts";

        $this->hosts = new HostsFile($this->fixturePath);
    }

    public function testHasHost()
    {
        $this->assertTrue($this->hosts->hasHost('host1'));
        $this->assertFalse($this->hosts->hasHost('-not-found-'));
    }

    public function testGetHosts()
    {
        $hosts = $this->hosts->getHosts('1.1.1.1');

        $this->assertCount(2, $hosts);
        $this->assertSame(array('host1', 'host1.tld'), $hosts);
    }

    public function testHasIp()
    {
        $this->assertTrue($this->hosts->hasIp('::1'));
        $this->assertTrue($this->hosts->hasIp('1.1.1.1'));
        $this->assertFalse($this->hosts->hasIp('-not-found-'));
    }

    public function testGetIp()
    {
        $this->assertEquals(array('1.1.1.1'),  $this->hosts->getIp('host1'));
        $this->assertEquals(array('127.0.0.1', '::1'),  $this->hosts->getIp('localhost'));
    }

    public function testAdd()
    {
        $ip = '9.9.9.9';
        $host = 'test.host';

        $this->assertFalse($this->hosts->hasIp($ip));
        $this->assertFalse($this->hosts->hasHost($host));

        $this->hosts->add($ip, $host);

        $this->assertTrue($this->hosts->hasIp($ip));
        $this->assertTrue($this->hosts->hasHost($host));
    }

    public function testHas()
    {
        $this->assertTrue($this->hosts->has('127.0.0.1', 'localhost'));
        $this->assertTrue($this->hosts->has('::1', 'localhost'));
    }

    public function testRemoveHost()
    {
        $ip = '1.1.1.1';
        $host = 'host1';

        $this->assertTrue($this->hosts->hasIp($ip));
        $this->assertTrue($this->hosts->hasHost($host));

        $this->hosts->removeHost($host);
        $this->assertFalse($this->hosts->hasHost($host));

        // more that 1 host for the ip, so the hasIp should be true
        $this->assertTrue($this->hosts->hasIp($ip));
    }

    public function testRemoveIp()
    {
        $ip = '1.1.1.1';
        $hosts = array('host1', 'host1.tld');

        $this->assertTrue($this->hosts->hasIp($ip));
        $this->assertTrue($this->hosts->hasHost($hosts[0]));
        $this->assertTrue($this->hosts->hasHost($hosts[1]));

        $this->hosts->removeIp($ip);


        $this->assertFalse($this->hosts->hasIp($ip));
        $this->assertFalse($this->hosts->hasHost($hosts[0]));
        $this->assertFalse($this->hosts->hasHost($hosts[1]));
    }

    public function testGetContent()
    {
        $testData= "#
# Generated by SagePHP HostsFile Component
# see https://github.com/SagePHP/
#

127.0.0.1\tlocalhost
::1\tlocalhost
1.1.1.1\thost1 host1.tld";

        $this->assertSame($testData, $this->hosts->getContent());
    }
}
